version: "3.7"

services:

  php:
    build:
      context: docker/image/php
      dockerfile: Dockerfile
    volumes:
      - ./:/srv/app:delegated

  node:
    build:
      context: docker/image/node
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app:delegated

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: toor

  search:
    image: elasticsearch:6.6.1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  http:
    build:
      context: docker/image/nginx
      dockerfile: Dockerfile
    volumes:
      - ./docker/image/nginx/default.conf.template:/etc/nginx/conf.d/default.template:delegated
      - ./:/srv/app:delegated
    depends_on:
      - php
    environment:
      NGINX_HOST: contacts-app.localhost
    ports:
      - "8091:80"
