# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    media_source_path: '%kernel.project_dir%/media'
    media_thumbnail_path: '%kernel.project_dir%/public/media'
    media_url_path: '/media'
    media_default_width: 200
    media_default_height: 200

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Media\ImageThumbnailGenerator:
        $sourcePath: '%media_source_path%'
        $thumbnailPath: '%media_thumbnail_path%'
        $width: '%media_default_width%'
        $height: '%media_default_height%'

    Elasticsearch\Client:
        factory: 'App\Elasticsearch\ClientBuilder:build'
        arguments: ['%env(ELASTICSEARCH_HOST)%']

    App\EventListener\ContactSearchEngineIndexer:
        tags:
            - name: doctrine.orm.entity_listener
              entity: App\Entity\Contact

    App\Elasticsearch\Index\ContactIndex:
        $namespace: '%env(ELASTICSEARCH_NAMESPACE)%'
